name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 2.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: 
    git:
      url: https://github.com/hayderux/flutter_cache_manager
  octo_image: ^1.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.0
  file: ^6.0.0

environment:
  flutter: ">=1.20.0 <2.0.0"
  sdk: ">=2.10.0 <3.0.0"
